### ISSUE TITLE
Is same name of config_registers fileds allowed ? 

### ISSUE THREAD

**Issue by Pe3ucTop** [ch32-rs/wchisp#3]
Great work ! 
Please comment on subject because of :
```
 - offset: 0x04
    name: DATA
    description: Customizable 2 byte data, DATA0, nDATA0, DATA1, nDATA1
    reset: 0xFF00FF00
    type: u32
    fields:
      - bit_range: [7, 0]
        name: DATA0
      - bit_range: [23, 16]
        name: DATA0
```
in `devices/0x17-CH32V30x.yaml`
